# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./scripts /app

# Install any needed packages specified in requirements.txt
RUN pip3 install flask requests==2.26.0 hdfs flask_socketio

# Make port 80 available to the world outside this container
EXPOSE 80 5000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "server.py"]
