# Use Ubuntu as the base image
FROM ubuntu:latest

# Set environment variables for Spark and Hadoop
ENV BASE_URL=https://archive.apache.org/dist/spark/
ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3.2.1
ENV HADOOP_URL=https://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz

# Install necessary packages
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    openjdk-8-jdk \
    python3 \
    python3-pip \
    gnupg \
    perl \
    procps \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME=${SPARK_HOME:-"/opt/spark"}
# Download and install Spark
RUN wget ${BASE_URL}/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz \
    && tar -xvzf spark-${SPARK_VERSION}-bin-hadoop3.tgz \
    && mv spark-${SPARK_VERSION}-bin-hadoop3 /opt/spark \
    && rm spark-${SPARK_VERSION}-bin-hadoop3.tgz

# Download Hadoop and import GPG key for verification
RUN set -x \
    && curl -fSL "$HADOOP_URL" -o /tmp/hadoop.tar.gz \
    && curl -fSL "$HADOOP_URL.asc" -o /tmp/hadoop.tar.gz.asc \
    && curl -fSL https://dist.apache.org/repos/dist/release/hadoop/common/KEYS -o /tmp/hadoop-keys \
    && gpg --import /tmp/hadoop-keys \
    && gpg --verify /tmp/hadoop.tar.gz.asc \
    && tar -xvf /tmp/hadoop.tar.gz -C /opt/ \
    && rm /tmp/hadoop.tar.gz* /tmp/hadoop-keys

# Create necessary directories and set up environment variables
RUN ln -s /opt/hadoop-$HADOOP_VERSION/etc/hadoop /etc/hadoop \
    && mkdir /opt/hadoop-$HADOOP_VERSION/logs \
    && mkdir /hadoop-data

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HADOOP_HOME=/opt/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=/etc/hadoop
ENV MULTIHOMED_NETWORK=1
ENV USER=root
ENV PATH=$HADOOP_HOME/bin/:$PATH
ENV PATH=$SPARK_HOME/sbin:/opt/spark/bin:$PATH
ENV LD_BIND_NOW=1

ENV SPARK_MASTER="spark://master:7077"
ENV SPARK_MASTER_HOST master
ENV SPARK_MASTER_PORT 7077

# Fix the value of PYTHONHASHSEED
# Note: this is needed when you use Python 3.3 or greater
ENV PYTHONHASHSEED=1

# Expose necessary ports
EXPOSE 8080 7077 6066 9000 9870 9864 8088 8042 22

# Add and set permissions for the entrypoint script
ADD entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["./entrypoint.sh"]

