global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'cadv2'
    static_configs:
      - targets: ['10.10.253.120:8080']
